name: i-Invested
favicon: null
layout_spectrum: 0.83919
typography_spectrum: 0.89162
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4d4c52'
    - '#24222f'
    - '#77726f'
    - '#692a35'
    - '#b9b4a8'
  brandStrength: 0.125
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
