typography_spectrum: 0.25308
color:
  brandColors:
    - '#4d4c52'
    - '#24222f'
    - '#77726f'
    - '#692a35'
    - '#b9b4a8'
  brandStrength: 0.5625
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.41656
analytics:
  google: null
  facebook: null
  twitter: null
name: i-Invested
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: i-Invested.com
purpose: []
