name: i-Invested
favicon: null
layout_spectrum: 0.53726
typography_spectrum: 0.78241
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfa'
    - '#d7d7d7'
    - '#a0a0a2'
    - '#141416'
    - '#775b45'
  brandStrength: 0.1875
  lightness: 0.9375
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
