name: i-Invested
favicon: null
layout_spectrum: 1
typography_spectrum: 0.77874905616045
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6875
  lightness: 0.39188913721591234
  saturation: 0.783888049190864
  rhythmicContrast: 0.1679485950153321
purpose: []
