name: i-Invested
favicon: null
layout_spectrum: 0.56757
typography_spectrum: 0.49347
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#15c1ff'
    - '#86d6f1'
    - '#45c2e5'
    - '#b9e5f3'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.783888049190864
  rhythmicContrast: 1
purpose: []
