name: i-Invested
favicon: null
layout_spectrum: 0.51486
typography_spectrum: 0.49347
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#15c1ff'
    - '#c2c2c2'
    - '#535353'
    - '#838383'
  brandStrength: 1
  lightness: 0.875
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
